name: flutter_app_tutorial_amplify_storage
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  amplify_core: '<1.0.0'
  amplify_auth_cognito: '<1.0.0'
  amplify_storage_s3: '<1.0.0'
  flutter_login: ^1.0.14
  cupertino_icons: ^0.1.3
  fluttertoast: ^4.0.1
  image_picker: ^0.6.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  random_words: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/

